import { eq, sql } from "drizzle-orm";
import type { Database } from "@propertyx/database";
import * as s from "@propertyx/database";
import { putFile, sha256, scanAllListings, refreshLocationCounts } from "@propertyx/core";

/** Minimal single-page PDF (no dependencies) used for clearly-labelled sample documents. */
function samplePdf(lines: string[]) {
  const esc = (t: string) => t.replace(/[\\()]/g, (c) => `\\${c}`);
  const content = ["BT", "/F1 20 Tf", "72 760 Td", `(${esc(lines[0])}) Tj`, "/F1 12 Tf", ...lines.slice(1).flatMap((l) => ["0 -24 Td", `(${esc(l)}) Tj`]), "ET"].join("\n");
  const objs = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>",
    `<< /Length ${Buffer.byteLength(content)} >>\nstream\n${content}\nendstream`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
  ];
  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [];
  objs.forEach((o, i) => {
    offsets.push(Buffer.byteLength(pdf));
    pdf += `${i + 1} 0 obj\n${o}\nendobj\n`;
  });
  const xref = Buffer.byteLength(pdf);
  pdf += `xref\n0 ${objs.length + 1}\n0000000000 65535 f \n${offsets.map((o) => `${String(o).padStart(10, "0")} 00000 n \n`).join("")}`;
  pdf += `trailer\n<< /Size ${objs.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;
  return Buffer.from(pdf);
}

export async function postSeed(db: Database) {
  console.log("• sample verification documents");
  const requests = await db.select().from(s.verificationRequests).where(eq(s.verificationRequests.isSeed, true));
  for (const v of requests) {
    const kinds = v.requestedLevel >= 3 ? ["ownership"] : ["cnic_front", "cnic_back"];
    for (const kind of kinds) {
      const buf = samplePdf([
        "SAMPLE DOCUMENT - DEMO DATA",
        `Document type: ${kind.replace("_", " ")}`,
        `Subject: ${v.subjectType} ${v.subjectId.slice(0, 8)}`,
        "This file was generated by the Bismillah seed script for testing",
        "the verification workflow. It is not a real identity or ownership document.",
      ]);
      const key = `documents/seed/${v.id}-${kind}.pdf`;
      await putFile("private", key, buf);
      await db.insert(s.documents).values({ ownerId: v.submittedById, verificationRequestId: v.id, kind, storageKey: key, originalName: `${kind}-sample.pdf`, mime: "application/pdf", sizeBytes: buf.length, sha256: sha256(Buffer.concat([buf, Buffer.from(v.id + kind)])), isSeed: true });
    }
  }
  console.log("• fraud scan");
  const r = await scanAllListings(db);
  const [{ n }] = await db.select({ n: sql<number>`count(*)::int` }).from(s.fraudFlags);
  await db.update(s.fraudFlags).set({ isSeed: true });
  console.log(`  scanned ${r.scanned}, flagged ${r.flagged} listings (${n} flags)`);
  await refreshLocationCounts(db);
}
